### ISSUE TITLE
Extension crashes when editing file

### ISSUE THREAD

**Issue by akolbus** [tsqllint/tsqllint-vscode-extension#21]
I love the vscode extension, I use it often when bringing scripts up to standards.  However, I have found that when I am making changes to the file, the extension crashes and stops providing that sweet sweet highlighting.  To get it back, I have to disable the extension, reload, enable the extension, and reload again.  

Here is the error output when this happens.  It appears to be related to contention on the temp file used for linting, and/or a null reference exception:
```
{ Error: EBUSY: resource busy or locked, open 'C:\Users\akolbus\AppData\Local\Temp\1\{nameOfTheFileImEditing}.tmp'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at ValidateBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:89:8)
    at documents.onDidChangeContent (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:33:5)
    at CallbackList.invoke (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at connection.onDidChangeTextDocument (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-languageserver\lib\main.js:194:46)
    at handleNotification (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    at processMessageQueue (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:255:17)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\Users\\akolbus\\AppData\\Local\\Temp\\1\\{nameOfTheFileImEditing}.tmp' }
{ Error: EBUSY: resource busy or locked, open 'C:\Users\akolbus\AppData\Local\Temp\1\{nameOfTheFileImEditing}.tmp'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at ValidateBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:89:8)
    at documents.onDidChangeContent (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:33:5)
    at CallbackList.invoke (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at connection.onDidChangeTextDocument (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-languageserver\lib\main.js:194:46)
    at handleNotification (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    at processMessageQueue (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:255:17)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\Users\\akolbus\\AppData\\Local\\Temp\\1\\{nameOfTheFileImEditing}.tmp' }
c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13
        const colEnd = lines[line].length;
                                  ^

TypeError: Cannot read property 'length' of undefined
    at parseError (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13:35)
    at Array.map (native)
    at Object.parseErrors (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:6:25)
    at ValidateBuffer.LintBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:95:37)
    at ChildProcess.childProcess.on (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:81:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Info  - 12:21:52 PM] Connection to server got closed. Server will restart.
{ Error: EBUSY: resource busy or locked, open 'C:\Users\akolbus\AppData\Local\Temp\1\{nameOfTheFileImEditing}.tmp'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at ValidateBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:89:8)
    at documents.onDidChangeContent (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:33:5)
    at CallbackList.invoke (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at connection.onDidChangeTextDocument (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-languageserver\lib\main.js:194:46)
    at handleNotification (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    at processMessageQueue (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:255:17)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\Users\\akolbus\\AppData\\Local\\Temp\\1\\{nameOfTheFileImEditing}.tmp' }
c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13
        const colEnd = lines[line].length;
                                  ^

TypeError: Cannot read property 'length' of undefined
    at parseError (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13:35)
    at Array.map (native)
    at Object.parseErrors (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:6:25)
    at ValidateBuffer.LintBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:95:37)
    at ChildProcess.childProcess.on (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:81:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Info  - 12:21:57 PM] Connection to server got closed. Server will restart.
{ Error: EBUSY: resource busy or locked, open 'C:\Users\akolbus\AppData\Local\Temp\1\{nameOfTheFileImEditing}.tmp'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at ValidateBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:89:8)
    at documents.onDidChangeContent (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:33:5)
    at CallbackList.invoke (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at connection.onDidChangeTextDocument (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-languageserver\lib\main.js:194:46)
    at handleNotification (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    at processMessageQueue (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:255:17)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\Users\\akolbus\\AppData\\Local\\Temp\\1\\{nameOfTheFileImEditing}.tmp' }
c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13
        const colEnd = lines[line].length;
                                  ^

TypeError: Cannot read property 'length' of undefined
    at parseError (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13:35)
    at Array.map (native)
    at Object.parseErrors (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:6:25)
    at ValidateBuffer.LintBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:95:37)
    at ChildProcess.childProcess.on (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:81:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Info  - 12:21:58 PM] Connection to server got closed. Server will restart.
{ Error: EBUSY: resource busy or locked, open 'C:\Users\akolbus\AppData\Local\Temp\1\{nameOfTheFileImEditing}.tmp'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at ValidateBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:89:8)
    at documents.onDidChangeContent (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:33:5)
    at CallbackList.invoke (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at connection.onDidChangeTextDocument (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-languageserver\lib\main.js:194:46)
    at handleNotification (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    at processMessageQueue (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:255:17)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\Users\\akolbus\\AppData\\Local\\Temp\\1\\{nameOfTheFileImEditing}.tmp' }
{ Error: EBUSY: resource busy or locked, open 'C:\Users\akolbus\AppData\Local\Temp\1\{nameOfTheFileImEditing}.tmp'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at ValidateBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:89:8)
    at documents.onDidChangeContent (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:33:5)
    at CallbackList.invoke (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at connection.onDidChangeTextDocument (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-languageserver\lib\main.js:194:46)
    at handleNotification (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    at processMessageQueue (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:255:17)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\Users\\akolbus\\AppData\\Local\\Temp\\1\\{nameOfTheFileImEditing}.tmp' }
c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13
        const colEnd = lines[line].length;
                                  ^

TypeError: Cannot read property 'length' of undefined
    at parseError (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13:35)
    at Array.map (native)
    at Object.parseErrors (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:6:25)
    at ValidateBuffer.LintBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:95:37)
    at ChildProcess.childProcess.on (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:81:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Info  - 12:22:04 PM] Connection to server got closed. Server will restart.
{ Error: EBUSY: resource busy or locked, open 'C:\Users\akolbus\AppData\Local\Temp\1\{nameOfTheFileImEditing}.tmp'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1326:33)
    at ValidateBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:89:8)
    at documents.onDidChangeContent (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:33:5)
    at CallbackList.invoke (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at connection.onDidChangeTextDocument (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-languageserver\lib\main.js:194:46)
    at handleNotification (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    at processMessageQueue (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\node_modules\vscode-jsonrpc\lib\main.js:255:17)
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path: 'C:\\Users\\akolbus\\AppData\\Local\\Temp\\1\\{nameOfTheFileImEditing}.tmp' }
c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13
        const colEnd = lines[line].length;
                                  ^

TypeError: Cannot read property 'length' of undefined
    at parseError (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:13:35)
    at Array.map (native)
    at Object.parseErrors (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\parseError.js:6:25)
    at ValidateBuffer.LintBuffer (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:95:37)
    at ChildProcess.childProcess.on (c:\Users\akolbus\.vscode\extensions\tsqllint.tsqllint-1.2.0\server\out\server.js:81:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[Error - 12:22:06 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by goldmane** [comment]
@akolbus  I also have the utility installed via npm for the cli and fixed this issue by running `tsqllint --init --force` - after that, restarted vsCode and everything was working again. Hope it helps.

**Comment by akolbus** [comment]
@nathan-boyd I'm excited for 1.3.0 to confirm that #24 will fix this issue for me.  I see the release was tagged a few days ago, do you know when the update will be available in the VSCode marketplace?
